Check if angular object is defined before deferencing
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getScopeName (fts.js:1255)
    at updatePreview (fts.js:1316)
    at ZoneDelegate.invokeTask (zone.js:431)
    at Object.onInvokeTask (core.js:26247)
    at ZoneDelegate.invokeTask (zone.js:430)
    at Zone.runTask (zone.js:198)
    at ZoneTask.invokeTask (zone.js:513)
    at ZoneTask.invoke (zone.js:502)
    at timer (zone.js:3041)

Change-Id: I5828e43e1320d6d3aab6497e5b3cb144eb95f0ad
Reviewed-on: http://review.couchbase.org/c/cbft/+/152718
Tested-by: Abhinav Dangeti <abhinav@couchbase.com>
Well-Formed: Build Bot <build@couchbase.com>
Reviewed-by: Abhinav Dangeti <abhinav@couchbase.com>